### ISSUE TITLE
Deprecation warning on final class extension

### ISSUE THREAD

**Issue by BenoitDuffez** [symfony/monolog-bundle#452] opened 2023-02-16 22:42 UTC
`Monolog\Logger` extends `Symfony\Bridge\Monolog\Logger` which is final:

```
Remaining indirect deprecation notices (1)
  1x: The "Monolog\Logger" class is considered final. It may change without further notice as of its next major version. You should not extend it from "Symfony\Bridge\Monolog\Logger".
```

**Comment by derrabus** [comment] 2023-02-16 23:38
Duplicate of symfony/symfony#47096

**Closed by derrabus** 2023-02-16 23:38 UTC
