### ISSUE TITLE
Segmentation fault (core dumped) with symfony_mailer handler

### ISSUE THREAD

**Issue by ahmed-bhs** [symfony/monolog-bundle#367] opened 2020-10-10 22:09 UTC
Q | A
-- | --
Bug report? | yes
Feature request? | no
BC Break report? | no
RFC? | no
Symfony version | 4.4.13
monolog/monolog | 2.1.1
symfony/monolog-bridge | v5.1.1
symfony/monolog-bundle | v3.6.0

I'm trying  to configure Monolog to send an email when an error occurs within my application. This configuration looks correct but every time I launch bin/console cache:clear, I get the "Segmentation fault (core dumped)" error.

This is my monolog config:

        main:
            type:         fingers_crossed
            action_level: critical
            handler:      deduplicated
            channels: ["!event", "!console"]
        deduplicated:
            type:    deduplication
            time: 10
            handler: symfony_mailer
        symfony_mailer:
            type:       symfony_mailer
            from_email: '%env(SENDER)%'
            to_email:   'my mail@gmail.com'
            subject:    'An Error Occurred! '
            level:      critical
            formatter:  monolog.formatter.html
            content_type: text/html

Any help would be greatly appreciated!
If you need more information, just let me know :)

**Comment by lyrixx** [comment] 2020-10-12 15:48
Hello, could you create a small reproducer? Thanks

**Comment by adrien-f** [comment] 2020-11-09 12:40
👋 Hey I think we're hitting that issue as well, I've dumped the core and looked into it with GDB: 

```
gdb) zbacktrace
[0x7faeaf722560] preg_replace_callback("/%%|%([^%\s]+)%/", object[0x7faeaf7225c0], "warn") [internal function]
[0x7faeaf7224b0] Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->resolveString("warn", array(0)[0x7faeaf722510]) /var/www/vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php:219
[0x7faeaf7223e0] Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->resolveValue("warn") /var/www/vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php:187
[0x7faeaf722280] Symfony\Component\DependencyInjection\ContainerBuilder->resolveEnvPlaceholders("warn", true, reference) /var/www/vendor/symfony/dependency-injection/ContainerBuilder.php:1416
[0x7faeaf722180] Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationContainerBuilder->resolveEnvPlaceholders("warn", true) /var/www/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php:222
[0x7faeaf7220d0] Symfony\Bundle\MonologBundle\DependencyInjection\MonologExtension->levelToMonologConst("warn", object[0x7faeaf722130]) /var/www/vendor/symfony/monolog-bundle/DependencyInjection/MonologExtension.php:60
[0x7faeaf722020] Symfony\Bundle\MonologBundle\DependencyInjection\MonologExtension->levelToMonologConst("warn", object[0x7faeaf722080]) /var/www/vendor/symfony/monolog-bundle/DependencyInjection/MonologExtension.php:66
[0x7faeaf721f70] Symfony\Bundle\MonologBundle\DependencyInjection\MonologExtension->levelToMonologConst("warn", object[0x7faeaf721fd0]) /var/www/vendor/symfony/monolog-bundle/DependencyInjection/MonologExtension.php:66
[0x7faeaf721ec0] Symfony\Bundle\MonologBundle\DependencyInjection\MonologExtension->levelToMonologConst("warn", object[0x7faeaf721f20]) /var/www/vendor/symfony/monolog-bundle/DependencyInjection/MonologExtension.php:66
[0x7faeaf721e10] Symfony\Bundle\MonologBundle\DependencyInjection\MonologExtension->levelToMonologConst("warn", object[0x7faeaf721e70]) /var/www/vendor/symfony/monolog-bundle/DependencyInjection/MonologExtension.php:66
... infinite loop
```

It feels like we're hitting a recursion here: https://github.com/symfony/monolog-bundle/commit/541e6e56a0b114ddf1dbd08c7392337677b48cae#diff-3ee12206c3b122be4593dbfdb19397c16b3d337f759fad3bde6c785d6f1261c0R66

Part of our config:

```
monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: warn
            handler:      main_group
            channels:     ["!messenger"]
```

**Comment by jderusse** [comment] 2020-11-09 12:47
Sound like a dupplicate of https://github.com/symfony/symfony/issues/38970
Could you please give a try to 4.4-dev or apply https://github.com/symfony/symfony/pull/38980 and https://github.com/symfony/symfony/pull/39021  ?

**Comment by adrien-f** [comment] 2020-11-09 12:50
Apologies @jderusse but we thought our segfault was linked to this issue while it does not look like it in the end (we also don't use the symfony_mailer).

**Comment by greg0ire** [comment] 2020-11-09 12:51
@jderusse the stack trace looks quite different from the one in the issue you linked. The infinite loop happens here: https://github.com/symfony/monolog-bundle/blob/541e6e56a0b114ddf1dbd08c7392337677b48cae/DependencyInjection/MonologExtension.php#L45-L70

**Comment by greg0ire** [comment] 2020-11-09 12:53
@adrien-f  in the config, should it be `warning` instead of `warn`? https://github.com/Seldaek/monolog/blob/39637a5d0e98068d98189ce48a87f3dd61455429/src/Monolog/Logger.php#L53

**Comment by adrien-f** [comment] 2020-11-09 13:11
Yes it should indeed by `warning`. This did not fail before because `constant()` returned `NULL` here before.

**Comment by greg0ire** [comment] 2020-11-09 13:15
Should https://github.com/symfony/monolog-bundle/blob/541e6e56a0b114ddf1dbd08c7392337677b48cae/DependencyInjection/MonologExtension.php#L65-L67 be moved inside the `try` block https://github.com/symfony/monolog-bundle/blob/541e6e56a0b114ddf1dbd08c7392337677b48cae/DependencyInjection/MonologExtension.php#L59-L63 @lyrixx ?

**Comment by jderusse** [comment] 2020-11-09 13:37
the `resolveEnvPlaceholders` methods does not throw an exception if the value is not a env placeholder, it simply returns the input value.
If opened #373 to fix it

**Comment by jderusse** [comment] 2020-11-09 15:19
unhide my comment https://github.com/symfony/monolog-bundle/issues/367#issuecomment-723991688 
I think this issue is solved by https://github.com/symfony/symfony/pull/38980

**Comment by do-web** [comment] 2020-11-22 11:17
@jderusse i have the same problem, how could i solve this?

**Comment by jderusse** [comment] 2020-11-22 11:51
> @jderusse i have the same problem, how could i solve this?

Should be fixed by the PR mentioned in my previous comment (5.2 RC2).
Or by the (not yet merged) PR https://github.com/symfony/symfony/pull/39129

**Closed** 2021-03-21 17:37 UTC
