### ISSUE TITLE
Lazy loaded Swift_Message can cause unserialize errors when using file spool

### ISSUE THREAD

**Issue by mekras** [symfony/monolog-bundle#117] opened 2015-04-03 08:49 UTC
When storing message in file it will be serialized with class name like `Swift_Message_000000003b027a18000000005cb90b1f`. After container rebuild this name will change. So if cache was cleared after message stored but before `swiftmailer:spool:send` command executed there will be error `Catchable Fatal Error: Argument 1 passed to Swift_Transport_MailTransport::send() must implement interface Swift_Mime_Message, instance of __PHP_Incomplete_Class given`.

This is a rare but troublesome case.

**Comment by mekras** [comment] 2015-06-08 13:54
How about adding option to disable lazy loading [here](https://github.com/symfony/MonologBundle/blob/v2.7.1/DependencyInjection/MonologExtension.php#L395)?

**Comment by Seldaek** [comment] 2015-06-19 00:28
Do you want to send a PR for it? I don't see a problem with making it optional, although it would be nicer if it was fixed upstream.. I find it strange that such classes end up in the spool. I would think the lazy loading is just delaying the creation until we use the message, but once it is sent to Swift it should really store it in a way that can be reloaded not based on the cache settings :/

**Comment by mekras** [comment] 2015-06-22 07:19
OK, I'll try.

**Comment by mekras** [comment] 2015-06-23 09:55
@Seldaek wrote:
> I would think the lazy loading is just delaying the creation until we use the message

Yes, for this purpose a proxy class with a random name is created instead of Swift_Message class. I think this is not an upstream problem but a reasonable solution.

To keep Swift_Message lazy its descendant in MonologBundle can be created with custom serialization method. Method can check for VirtualProxyInterface on $this and return serialization of the real message object, not his proxy. It's quite cumbersome but how about this?

**Comment by mekras** [comment] 2015-06-23 11:36
PR to add "lazy" option: #132

**Comment by Seldaek** [comment] 2015-07-12 10:01
I can merge your PR as a workaround but I think the proxy class created by symfony should handle serialization gracefully (i.e. instantiate itself fully at that point and then serialize the instance). Or did I misunderstand you? Still sounds like something that could be fixed in symfony.

**Comment by stof** [comment] 2015-08-01 15:51
@Seldaek the problem is that ``serialize($object)`` will always register the class of the object being serialized, and reuse the same class on unserialization. And this is outside the control of the object.

so the class must exist again to deserialize. The only way to change that would be to change the calling code to stop using PHP serialization

**Comment by Seldaek** [comment] 2015-08-01 15:59
Oh right that sucks. I merged the workaround PR then. I guess it should be in the docs that if not using the memory spool people should disable lazy logging as well? Or did I misunderstand that?

cc @ryanweaver

**Comment by xabbuh** [comment] 2015-08-02 08:05
I doubt @ryanweaver has anything to say here. :)

/cc @weaverryan

**Comment by xabbuh** [comment] 2015-08-04 21:12
see symfony/symfony-docs#5596

**Comment by lyrixx** [comment] 2019-05-18 13:10
I'm going to close this issue as we can not dot anything here. 
The class should exist in the code base to be able to unserialise it.
But @xabbuh added a not in the documentation https://github.com/symfony/symfony-docs/commit/f20fd8d5da503fe6357fb9b405c1c9fd8211b010

Thanks

**Closed by lyrixx** 2019-05-18 13:10 UTC
