### ISSUE TITLE
[Bug][symfony_mailer] Cannot use json environment processor to generate array for to_email configuration.

### ISSUE THREAD

**Issue by silverbackdan** [symfony/monolog-bundle#381] opened 2021-01-05 15:11 UTC
If I use this config:
```
monolog:
    handlers:
        symfony_mailer:
            type: symfony_mailer
            ...
            to_email: '%env(json:LOGGER_EMAIL_TO)%'
            ...
```

With the environment variable:
```
LOGGER_EMAIL_TO='["email@website.com","email2@website.com"]'
```

An error is returned:
```
 Invalid type for path "monolog.handlers.symfony_mailer.to_email.0". Expected one of "bool", "int", "float", "string", but got "array". 
```

I can't figure out why the first item in the array would be another array, and I'm unsure whether this is related to the bundle of the environment processor from Symfony core - although I would have thought the core functionality for this would be well tested.

I've probably done something really silly but I can't see what it is.

**Comment by jderusse** [comment] 2021-03-21 17:33
The parameter `to_email` does not accept env variables.

**Comment by jderusse** [comment] 2021-03-21 17:36
Duplicate of #381

**Closed by jderusse** 2021-03-21 17:36 UTC
