### ISSUE TITLE
Symfony 5 is required for Monolog 2 support. Please downgrade Monolog to version 1.

### ISSUE THREAD

**Issue by arashdeepsinghazad** [symfony/monolog-bundle#332] opened 2019-11-30 14:09 UTC
I am using Symfony 3.4.
And it gives "Symfony 5 is required for Monolog 2 support. Please downgrade Monolog to version 1."
I tried many methods to make monolog/monolog[2.0.1] -> monolog/monolog[1.25.0]
My symfony/monolog-bundle is 3.1.0 and the same version is working on my other symfony 3.4 projects.

**Comment by xabbuh** [comment] 2019-11-30 22:25
duplicate of #330

**Closed by xabbuh** 2019-11-30 22:25 UTC
